spring:
  application:
    name: member-service
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        file-extension: yml
        group: DEFAULT-GROUP
        namespace: public
  profiles:
    active: dev
